import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

/**
 * ─────────────────────────────────────────────────────────────────────────
 * CODEABLE WEB GUARDRAILS
 *
 * Generated by `codeable-web guardrails`. These rules encode the architecture
 * so it can't quietly erode — a convention the linter enforces survives; one
 * that lives only in a doc lasts until the first deadline.
 *
 * The judgment-based rules they CAN'T express (is this domain in the right role
 * folder? is this component doing business logic?) are what `/web-audit` and
 * `codeable-web doctor` are for.
 *
 * Re-run `codeable-web guardrails` after adding a role to regenerate the
 * import-boundary zones.
 * ─────────────────────────────────────────────────────────────────────────
 */
const eslintConfig = defineConfig([
  // eslint-config-next already bundles jsx-a11y; adding the plugin again is a
  // "cannot redefine plugin" error, so a11y rules are raised below instead.
  ...nextVitals,
  ...nextTs,

  globalIgnores([".next/**", "out/**", "build/**", "next-env.d.ts"]),

  {
    name: "codeable/architecture",
    rules: {
      // ── Layering ───────────────────────────────────────────────────────
      // Dependencies point inward. Roles never import each other; shared
      // layers never import features; a symbol two of them need moves UP.
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["../*"],
              message:
                "Use the '@/*' alias instead of relative parent imports (CQ-002).",
            },
          ],
        },
      ],

      // ── Logging ────────────────────────────────────────────────────────
      // One seam, so production has one place to wire a real service.
      "no-console": "error",

      // ── Native dialogs ─────────────────────────────────────────────────
      "no-alert": "error",

      // ── Type safety ────────────────────────────────────────────────────
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-non-null-assertion": "error",

      // ── Accessibility (above next's defaults) ──────────────────────────
      "jsx-a11y/alt-text": "error",
      "jsx-a11y/anchor-has-content": "error",
      "jsx-a11y/aria-props": "error",
      "jsx-a11y/label-has-associated-control": "error",
      "jsx-a11y/role-has-required-aria-props": "error",
      "jsx-a11y/no-autofocus": "off", // autofocusing a form's first field is intentional

      // ── Transport & env discipline ─────────────────────────────────────
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "MemberExpression[object.object.name='process'][object.property.name='env']",
          message:
            "Read environment variables from '@/config/env' — only config/env.ts may touch process.env.",
        },
        {
          selector: "CallExpression[callee.name='fetch']",
          message:
            "Call the backend through 'backendClient' (@/lib/http) — a raw fetch skips auth, envelope unwrapping, refresh-on-401 and abort handling.",
        },
      ],
    },
  },

  {
    name: "codeable/boundaries:shared-layers",
    files: [
      "src/lib/**",
      "src/components/ui/**",
      "src/components/shared/**",
      "src/components/form/**",
      "src/types/**",
      "src/constants/**",
      "src/hooks/**",
    ],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@/features/**"],
              message:
                "Shared layers must not import from features/ — that inverts the dependency direction (AR-003).",
            },
          ],
        },
      ],
    },
  },

  {
    // Infrastructure DEFINES the primitives the rules above point at, so it's
    // exempt — narrowly, by path.
    name: "codeable/infrastructure-exemptions",
    files: [
      "src/lib/http/**",
      "src/lib/auth/session.ts",
      "src/lib/reporting.ts",
      "src/config/env.ts",
      "src/proxy.ts",
      "src/middleware.ts",
      "src/app/api/**",
    ],
    rules: {
      "no-restricted-syntax": "off",
      "no-console": "off",
    },
  },

  {
    // Tooling and tests run in Node, outside the app's runtime, and legitimately
    // read raw env. They aren't part of the shipped bundle.
    name: "codeable/tooling",
    files: ["*.config.{ts,mjs,js}", "e2e/**", "src/**/*.test.{ts,tsx}"],
    rules: {
      "no-restricted-syntax": "off",
      "no-console": "off",
    },
  },

  {
    // shadcn primitives are generated — recolor via tokens, don't fight them.
    name: "codeable/generated-ui",
    files: ["src/components/ui/**"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "jsx-a11y/heading-has-content": "off",
      "jsx-a11y/anchor-has-content": "off",
    },
  },
]);

export default eslintConfig;
