/**
 * The ESLint guardrail pack, as generated source.
 *
 * A rule the linter enforces survives; one that lives only in a document lasts
 * until the first deadline. These encode the architecture so it can't quietly
 * erode — import boundaries, transport discipline, the logging seam, env access.
 *
 * Emitted as a config FILE rather than shipped as an npm dependency because the
 * import-boundary zones are generated from the project's actual roles: a rule
 * that says "admin must not import lager" has to know those names. The file is
 * readable, greppable and editable in place, which for something a team will
 * argue with is worth more than a version number.
 *
 * `severity` lets an existing codebase adopt at "warn" and ratchet up, rather
 * than facing hundreds of errors on day one and turning the whole thing off.
 */

import fs from "fs-extra";
import path from "node:path";
import { formatSource } from "./format.js";

export interface GuardrailOptions {
  roles: string[];
  severity: "error" | "warn";
  /** Include the TanStack Query plugin (skip if the project doesn't use it). */
  withQuery: boolean;
}

/**
 * Import-boundary rules, as one flat-config block per boundary.
 *
 * `no-restricted-imports` has no notion of "who is importing" — its patterns
 * apply to whatever files the block matches. So a directional rule ("admin must
 * not import lager") has to be expressed as a `files` scope plus the patterns
 * that scope may not use, which means one block per role.
 */
function boundaryBlocks(roles: string[], severity: string): string {
  const featureRoles = roles.filter((role) => role !== "common");

  const roleBlocks = featureRoles.map((role) => {
    const forbidden = featureRoles
      .filter((other) => other !== role)
      .map((other) => `"@/features/${other}/*", "@/features/${other}/**"`)
      .join(", ");

    if (!forbidden) return "";

    return `  {
    name: "jinn-web/boundaries:${role}",
    files: ["src/features/${role}/**"],
    rules: {
      "no-restricted-imports": [
        "${severity}",
        {
          patterns: [
            {
              group: [${forbidden}],
              message:
                "Roles must not import each other. Move the shared symbol up to features/common/ or components/shared/ (AR-002).",
            },
          ],
        },
      ],
    },
  },`;
  });

  const commonBlock = featureRoles.length
    ? `  {
    name: "jinn-web/boundaries:common",
    files: ["src/features/common/**"],
    rules: {
      "no-restricted-imports": [
        "${severity}",
        {
          patterns: [
            {
              group: [${featureRoles.map((role) => `"@/features/${role}/**"`).join(", ")}],
              message:
                "common/ must not import a role folder — dependencies point inward, never outward (AR-002).",
            },
          ],
        },
      ],
    },
  },`
    : "";

  const sharedBlock = `  {
    name: "jinn-web/boundaries:shared-layers",
    files: [
      "src/lib/**",
      "src/components/ui/**",
      "src/components/shared/**",
      "src/components/form/**",
      "src/components/layout/**",
      "src/types/**",
      "src/constants/**",
      "src/hooks/**",
      "src/i18n/**",
      "src/validations/**",
      "src/config/**",
    ],
    rules: {
      "no-restricted-imports": [
        "${severity}",
        {
          patterns: [
            {
              group: ["@/features/**"],
              message:
                "Shared layers must not import from features/ — that inverts the dependency direction (AR-003).",
            },
          ],
        },
      ],
    },
  },`;

  return [...roleBlocks, commonBlock, sharedBlock].filter(Boolean).join("\n\n");
}

export function renderGuardrailConfig(options: GuardrailOptions): string {
  const { roles, severity, withQuery } = options;

  return `import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
${withQuery ? 'import tanstackQuery from "@tanstack/eslint-plugin-query";\n' : ""}
/**
 * ─────────────────────────────────────────────────────────────────────────
 * CODEABLE WEB GUARDRAILS
 *
 * Generated by \`jinn-web\`. These rules encode the architecture
 * so it can't quietly erode — a convention the linter enforces survives; one
 * that lives only in a doc lasts until the first deadline.
 *
 * The judgment-based rules they CAN'T express (is this domain in the right role
 * folder? is this component doing business logic?) are what \`/web-audit\` and
 * \`jinn-web doctor\` are for.
 *
 * Re-run \`jinn-web guardrails\` after adding a role to regenerate the
 * import-boundary zones.
 * ─────────────────────────────────────────────────────────────────────────
 */
const eslintConfig = defineConfig([
  // eslint-config-next already bundles jsx-a11y; adding the plugin again is a
  // "cannot redefine plugin" error, so a11y rules are raised below instead.
  ...nextVitals,
  ...nextTs,
${withQuery ? '  ...tanstackQuery.configs["flat/recommended"],\n' : ""}
  globalIgnores([".next/**", "out/**", "build/**", "next-env.d.ts"]),

  {
    name: "jinn-web/architecture",
    rules: {
      // ── Layering ───────────────────────────────────────────────────────
      // Dependencies point inward. Roles never import each other; shared
      // layers never import features; a symbol two of them need moves UP.
      "no-restricted-imports": [
        "${severity}",
        {
          patterns: [
            {
              group: ["../*"],
              message:
                "Use the '@/*' alias instead of relative parent imports (CQ-002).",
            },
          ],
        },
      ],

      // ── Logging ────────────────────────────────────────────────────────
      // One seam, so production has one place to wire a real service.
      "no-console": "${severity}",

      // ── Native dialogs ─────────────────────────────────────────────────
      "no-alert": "${severity}",

      // ── Type safety ────────────────────────────────────────────────────
      "@typescript-eslint/no-explicit-any": "${severity}",
      "@typescript-eslint/no-non-null-assertion": "${severity}",

      // ── Accessibility (above next's defaults) ──────────────────────────
      "jsx-a11y/alt-text": "${severity}",
      "jsx-a11y/anchor-has-content": "${severity}",
      "jsx-a11y/aria-props": "${severity}",
      "jsx-a11y/label-has-associated-control": "${severity}",
      "jsx-a11y/role-has-required-aria-props": "${severity}",
      "jsx-a11y/no-autofocus": "off", // autofocusing a form's first field is intentional

      // ── Transport & env discipline ─────────────────────────────────────
      "no-restricted-syntax": [
        "${severity}",
        {
          selector:
            "MemberExpression[object.object.name='process'][object.property.name='env']",
          message:
            "Read environment variables from '@/config/env' — only config/env.ts may touch process.env.",
        },
        {
          selector: "CallExpression[callee.name='fetch']",
          message:
            "Call the backend through 'backendClient' (@/lib/http) — a raw fetch skips auth, envelope unwrapping, refresh-on-401 and abort handling.",
        },
      ],
    },
  },

${boundaryBlocks(roles, severity)}

  {
    // Infrastructure DEFINES the primitives the rules above point at, so it's
    // exempt — narrowly, by path.
    name: "jinn-web/infrastructure-exemptions",
    files: [
      "src/lib/http/**",
      "src/lib/auth/session.ts",
      "src/lib/reporting.ts",
      "src/config/env.ts",
      "src/proxy.ts",
      "src/middleware.ts",
      "src/app/api/**",
    ],
    rules: {
      "no-restricted-syntax": "off",
      "no-console": "off",
    },
  },

  {
    // Tooling and tests run in Node, outside the app's runtime, and legitimately
    // read raw env. They aren't part of the shipped bundle.
    name: "jinn-web/tooling",
    files: ["*.config.{ts,mjs,js}", "e2e/**", "src/**/*.test.{ts,tsx}"],
    rules: {
      "no-restricted-syntax": "off",
      "no-console": "off",
    },
  },

  {
    // shadcn primitives are generated — recolor via tokens, don't fight them.
    name: "jinn-web/generated-ui",
    files: ["src/components/ui/**"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "jsx-a11y/heading-has-content": "off",
      "jsx-a11y/anchor-has-content": "off",
    },
  },
]);

export default eslintConfig;
`;
}

/**
 * Re-render the pack after the role list changes.
 *
 * The import-boundary zones are generated FROM the roles, so a project that
 * gains or loses one has a config that no longer describes it — the new role
 * gets no zone at all, which is a silent hole rather than a visible error.
 *
 * Only rewrites a file that is recognisably this pack: a hand-written or
 * ejected config is the user's, and clobbering it would be the worst kind of
 * surprise. Severity and the Query plugin are read back off the existing file
 * so a project that adopted at "warn" stays there.
 *
 * Returns true when the file was rewritten.
 */
export async function refreshGuardrailConfig(
  root: string,
  roles: string[],
): Promise<boolean> {
  const configPath = path.join(root, "eslint.config.mjs");
  if (!(await fs.pathExists(configPath))) return false;

  const existing = await fs.readFile(configPath, "utf8");
  if (!existing.includes(`name: "jinn-web/architecture"`)) return false;

  const severity = existing.includes(`"no-console": "warn"`) ? "warn" : "error";
  const withQuery = existing.includes("@tanstack/eslint-plugin-query");

  const rendered = await formatSource(
    renderGuardrailConfig({ roles, severity, withQuery }),
    configPath,
  );
  if (rendered === existing) return false;

  await fs.writeFile(configPath, rendered, "utf8");
  return true;
}
